services:

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio-data:/data

  create-bucket:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      - minio
    entrypoint: ["/bin/sh","-c"]
    command: >
      "
      set -euo pipefail;
      mc alias set local http://minio:9000 minioadmin minioadmin123;
      # Create bucket if it doesn't exist
      if ! mc ls local/tfstate >/dev/null 2>&1; then
        mc mb local/tfstate;
        mc anonymous set download local/tfstate; # optional, keep private if you want
      fi;
      echo 'MinIO bucket tfstate ready.';
      tail -f /dev/null;
      "
    restart: unless-stopped

volumes:
  minio-data:
