persistence:
  enabled: true
  size: 128Mi
  #size: 1Gi
  name: traefik-certs

certificatesResolvers:
  letsencrypt:
    acme:
      email: marko.korhonen@gmail.com
      #caServer: https://acme-v02.api.letsencrypt.org/directory # Production server
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # Staging server
      dnsChallenge:
        provider: azuredns
      storage: /data/acme.json

deployment:
  hostAliases:
    - ip: "4.210.41.109"
      hostnames:
        - "azure-terraform.ineen.net"
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "ls -la /; touch /data/acme.json; chmod -v 600 /data/acme.json"]
      volumeMounts:
        - mountPath: /data
          name: traefik-certs

podSecurityContext:
  fsGroup: 65532
  fsGroupChangePolicy: "OnRootMismatch"

ingressRoute:
  dashboard:
    enabled: true

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
